language: python
python: 3.6

sudo: required

stages:
  - name: test
  - name: release
    if: tag IS present
  - name: deploy
    if: tag IS present


jobs:
  include:
    - name: 'Unit tests'
      script:
        - echo "TODO"

    - name: 'Integration test: analyzer server'
      install:
        - pip3 install -r requirements.txt
      script:
        - ./_tools/install-lookout-latest.sh
        - (python3 sonarcheck_analyzer.py |& tee -a ../analyzer.log)&
        - ../lookout-sdk review --log-level=debug "ipv4://localhost:2022"
      after_failure:
        - cat ../analyzer.log
        - cat ../lookout-install.log

    - name: 'Push image to Docker Hub'
      stage: release
      script:
        - DOCKER_PUSH_LATEST=true make docker-push
    - name: 'Deploy to staging'
      stage: deploy
      install:
        - make install-helm
      script:
        - HELM_RELEASE=lookout-gosonarcheck-analyzer HELM_CHART=lookout-gosonarcheck-analyzer K8S_NAMESPACE=lookout HELM_ARGS="--tiller-namespace=lookout --repo https://src-d.github.io/charts/ --set image.tag=$TRAVIS_TAG -f .helm_staging.yml" make deploy
